add Next web3js to front-end templates
matter-labs/zksync-frontend-templates pull request #14
Opened 2024-08-08 20:00 UTC by luu-alex

# What :computer: 
* Adds a next web3.js to front-end templates examples
* Second thing updated with this PR
* Third thing updated with this PR

# Why :hand:
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR

# Evidence :camera:
Include screenshots, screen recordings, or `console` output here demonstrating that your changes work as intended

# Notes :memo:
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

2024-08-16 16:27 UTC, jennyg0 reviewed
thank you for the pr, looks great! have a few minor comments

2024-08-16 16:27 UTC, jennyg0 commented on templates/react/next-web3js/src/components/Context.tsx
> +  }
goerli can be removed

2024-08-16 16:28 UTC, jennyg0 commented on templates/react/next-web3js/src/components/Balance.tsx
> +import { Web3 } from 'Web3';
should this be `from 'web3'`, getting a casing error here

2024-08-16 16:29 UTC, jennyg0 commented on templates/react/next-web3js/src/components/Context.tsx
> +    name: "zkSync Sepolia Testnet",
ZKsync here too

2024-08-16 16:30 UTC, jennyg0 commented on templates/react/next-web3js/src/components/contracts.ts
> +  address: "0x6Ff473f001877D553833B6e312C89b3c8fACa7Ac", // zkSync Era Sepolia Testnet DAI token address
ZKsync

2024-08-16 16:30 UTC, jennyg0 commented on templates/react/next-web3js/src/pages/index.tsx
> +                <strong>Make sure to connect your wallet to zkSync Testnet for full functionality</strong>
ZKsync here and in the title tag

2024-08-16 16:40 UTC, jennyg0 commented on templates/react/next-web3js/README.md
> +This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).
nice to have more specific readme like [this one](https://github.com/matter-labs/zksync-frontend-templates/tree/main/templates/react/next-wagmi#readme)

2024-08-19 11:49 UTC, luu-alex commented
Feedback has been addressed :) Thank you!

2024-08-20 23:40 UTC, jennyg0 commented on templates/react/next-web3js/src/components/contracts.ts
> +  address: "0x6Ff473f001877D553833B6e312C89b3c8fACa7Ac", // ZKsync Era Sepolia Testnet DAI token address
thank you for the updates! sorry missed that official address for the DAI token is `0x604F0416e788779edB06c1A74a75FAad38384C6E`

2024-08-20 23:51 UTC, jennyg0 commented on templates/react/next-web3js/src/components/Context.tsx
> +      setNetwork(currentChain ?? { id: chainIdStr, name: null, rpcUrl: null, unsupported: true });
Getting a type error: Argument of type 'Chain | { id: string | undefined; name: null; rpcUrl: null; unsupported: true; }' is not assignable to parameter of type 'SetStateAction<Chain | null>'.

2024-08-20 23:51 UTC, jennyg0 commented on templates/react/next-web3js/src/components/Context.tsx
> +      web3.registerPlugin(zkSyncPlugin);
Also seeing a type error: Argument of type 'ZkSyncPlugin' is not assignable to parameter of type 'Web3PluginBase<unknown>'.

2024-08-21 14:00 UTC, luu-alex commented on templates/react/next-web3js/src/components/Context.tsx
> +      web3.registerPlugin(zkSyncPlugin);
This issue will be fixed when the next version of web3 ZkSyncPlugin is published

2024-08-21 14:01 UTC, luu-alex commented on templates/react/next-web3js/src/components/contracts.ts
> +  address: "0x6Ff473f001877D553833B6e312C89b3c8fACa7Ac", // ZKsync Era Sepolia Testnet DAI token address
Updated

2024-08-22 13:16 UTC, jennyg0 approved these changes

2024-08-22 20:49 UTC, jennyg0 commented on templates/react/next-web3js/src/components/Context.tsx
> +      web3.registerPlugin(zkSyncPlugin);
awesome @danforbes @luu-alex ! thank you for all the updates. one last thing is the casing looks like it was changed to `ZKsyncPlugin` from ZkSyncPlugin for the import.

2024-08-23 12:16 UTC, danforbes commented on templates/react/next-web3js/src/components/Context.tsx
> +      web3.registerPlugin(zkSyncPlugin);
Thank you for spotting that @jennyg0 🙏🏻 Should be taken care of now ✅

2024-08-23 13:57 UTC, jennyg0 approved these changes

2024-08-23 15:27 UTC, itsacoyote requested changes

2024-08-23 15:27 UTC, itsacoyote commented on templates/react/next-web3js/README.md
> +- [ZKsync Documentation](https://era.zksync.io/docs/dev) – learn about ZKsync features and API.
```suggestion
- [ZKsync Documentation](https://docs.zksync.io) – learn about ZKsync features and API.
```

2024-08-23 22:35 UTC, itsacoyote approved these changes

2024-08-23 23:08 UTC, jennyg0 approved these changes

2024-08-23 23:20 UTC, merged