Vite Web3Js frontend template
matter-labs/zksync-frontend-templates pull request #15
Opened 2024-08-09 10:56 UTC by Woafflation

# What :computer: 
* Adds a vite web3.js to front-end templates examples
* Second thing updated with this PR
* Third thing updated with this PR

# Why :hand:
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR

# Evidence :camera:
Include screenshots, screen recordings, or `console` output here demonstrating that your changes work as intended

2024-08-19 21:16 UTC, itsacoyote commented on templates/react/vite-web3js/README.md
> +- Install [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react) and add `plugin:react/recommended` & `plugin:react/jsx-runtime` to the `extends` list
Could you update this README so that it is more specific to this template for ZKsync CLI?
An example: https://github.com/matter-labs/zksync-frontend-templates/tree/main/templates/react/next-wagmi#readme

2024-08-22 19:18 UTC, Woafflation commented
@itsacoyote 

Thanks!
Updated PR

2024-08-23 15:08 UTC, itsacoyote requested changes
Just two last requests I missed, and everything else looks good 👍🏻

2024-08-23 15:08 UTC, itsacoyote commented on templates/react/vite-web3js/.gitignore
> +
Can we add .env files to the gitignore? 

```
# local env files

.env
.env\*.local
```

2024-08-23 15:08 UTC, itsacoyote commented on templates/react/vite-web3js/README.md
> +- [ZKsync Documentation](https://era.zksync.io/docs/dev) – learn about ZKsync features and API.
Our docs url changed, we're catching up on updating all the other templates 😅 
```suggestion
- [ZKsync Documentation](https://docs.zksync.io) – learn about ZKsync features and API.
```

2024-08-23 16:47 UTC, Woafflation commented
Updated PR!

@itsacoyote

2024-08-23 22:34 UTC, itsacoyote approved these changes

2024-08-23 22:34 UTC, merged